packages:
  - '.'
  - example
  - exampleForExpo

onlyBuiltDependencies:
  - '@evilmartians/lefthook'

linkWorkspacePackages: true

catalog:
  '@types/react': ^19.1.12
  '@types/react-dom': ^19.1.9
  react: 19.1.0
  react-dom: 19.1.0
  react-native: 0.81.5
