import type { ConfigContext, ExpoConfig } from 'expo/config';

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: 'example',
  slug: 'example',
  version: '1.0.0',
  orientation: 'portrait',
  icon: './assets/icon.png',
  userInterfaceStyle: 'light',
  newArchEnabled: true,
  splash: {
    image: './assets/splash-icon.png',
    resizeMode: 'contain',
    backgroundColor: '#ffffff',
  },
  scheme: 'exampleforexpo',
  ios: {
    supportsTablet: true,
    bundleIdentifier: 'iamportreactnative.example',
    buildNumber: '1',
    infoPlist: {
      LSApplicationQueriesSchemes: [
        'kftc-bankpay',
        'ispmobile',
        'itms-apps',
        'hdcardappcardansimclick',
        'smhyundaiansimclick',
        'shinhan-sr-ansimclick',
        'smshinhanansimclick',
        'kb-acp',
        'mpocket.online.ansimclick',
        'ansimclickscard',
        'ansimclickipcollect',
        'vguardstart',
        'samsungpay',
        'scardcertiapp',
        'lottesmartpay',
        'lotteappcard',
        'cloudpay',
        'nhappcardansimclick',
        'nonghyupcardansimclick',
        'citispay',
        'citicardappkr',
        'citimobileapp',
        'kakaotalk',
        'payco',
        'lpayapp',
        'hanamopmoasign',
        'wooripay',
        'nhallonepayansimclick',
        'hanawalletmembers',
        'chaipayment',
        'kb-auth',
        'hyundaicardappcardid',
        'com.wooricard.wcard',
        'lmslpay',
        'lguthepay-xpay',
        'liivbank',
        'supertoss',
        'newsmartpib',
        'ukbanksmartbanknonloginpay',
        'kakaobank',
      ],
      NSAppTransportSecurity: {
        NSAllowsArbitraryLoads: true,
        NSAllowsArbitraryLoadsInWebContent: true,
      },
    },
  },
  android: {
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      backgroundColor: '#ffffff',
    },
    edgeToEdgeEnabled: true,
    package: 'iamportreactnative.example',
    versionCode: 1,
    intentFilters: [
      {
        action: 'VIEW',
        category: ['DEFAULT', 'BROWSABLE'],
        data: {
          scheme: 'exampleforexpo',
        },
      },
    ],
  },
  web: {
    favicon: './assets/favicon.png',
  },
  plugins: [
    [
      'expo-build-properties',
      {
        android: {
          manifestQueries: {
            intent: [
              {
                action: 'android.intent.action.VIEW',
                category: ['android.intent.category.BROWSABLE'],
                data: {
                  scheme: 'https',
                },
              },
            ],
            package: [
              'kvp.jjy.MispAndroid320',
              'com.kftc.bankpay.android',
              'com.kbstar.liivbank',
              'com.nh.cashcardapp',
              'kr.co.kfcc.mobilebank',
              'com.knb.psb',
              'com.kakao.talk',
              'com.mysmilepay.app',
              'finance.chai.app',
              'com.nhnent.payapp',
              'com.hyundaicard.appcard',
              'viva.republica.toss',
              'com.shcard.smartpay',
              'com.shinhan.smartcaremgr',
              'com.hanaskard.paycla',
              'kr.co.samsungcard.mpocket',
              'com.kbcard.cxh.appcard',
              'nh.smart.nhallonepay',
              'kr.co.citibank.citimobile',
              'com.lcacApp',
              'com.lotte.lpay',
              'com.ssg.serviceapp.android.egiftcertificate',
              'com.inicis.kpay',
              'com.kbankwith.smartbank',
              'com.lguplus.paynow',
              'com.wooricard.smartapp',
              'com.lottemembers.android',
              'com.kt.ktauth',
              'com.lguplus.smartotp',
              'com.sktelecom.tauth',
              'com.wooribank.smart.npib',
              'com.kakaobank.channel',
              'com.shinhan.sbanking',
            ],
          },
        },
      },
    ],
  ],
});
